// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/zeroclaw.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -915225940;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_my_agent_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiZeroclawAddProvider({
    required String name,
    required String apiKey,
    required String model,
    required String baseUrl,
    required int priority,
  });

  Future<AgentStatus> crateApiZeroclawAgentStatus();

  String crateApiSimpleGreet({required String name});

  Future<AgentStatus> crateApiZeroclawInitAgent({
    required String dataDir,
    required String strategy,
  });

  Future<void> crateApiSimpleInitApp();

  Future<List<ProviderStatus>> crateApiZeroclawListProviders();

  Future<BigInt> crateApiZeroclawMemoryCount();

  Future<bool> crateApiZeroclawMemoryForget({required String key});

  Future<MemoryEntryDto?> crateApiZeroclawMemoryGet({required String key});

  Future<bool> crateApiZeroclawMemoryHealth();

  Future<List<MemoryEntryDto>> crateApiZeroclawMemoryList({
    String? category,
    String? sessionId,
  });

  Future<List<MemoryEntryDto>> crateApiZeroclawMemoryRecall({
    required String query,
    required int limit,
    String? sessionId,
  });

  Future<BigInt> crateApiZeroclawMemoryReindex();

  Future<void> crateApiZeroclawMemoryStore({
    required String key,
    required String content,
    required String category,
    String? sessionId,
  });

  Future<bool> crateApiZeroclawRemoveProvider({required String name});

  Future<String> crateApiZeroclawRunAgent({
    required String prompt,
    String? sessionId,
  });

  Future<String> crateApiZeroclawRunAgentWithProvider({
    required String prompt,
    required String providerName,
    String? sessionId,
  });

  Future<String> crateApiZeroclawSetRoutingStrategy({required String strategy});

  Future<bool> crateApiZeroclawUpdateProviderKey({
    required String name,
    required String newApiKey,
  });

  Future<bool> crateApiZeroclawUpdateProviderModel({
    required String name,
    required String newModel,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiZeroclawAddProvider({
    required String name,
    required String apiKey,
    required String model,
    required String baseUrl,
    required int priority,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(apiKey, serializer);
          sse_encode_String(model, serializer);
          sse_encode_String(baseUrl, serializer);
          sse_encode_u_32(priority, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawAddProviderConstMeta,
        argValues: [name, apiKey, model, baseUrl, priority],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawAddProviderConstMeta =>
      const TaskConstMeta(
        debugName: "add_provider",
        argNames: ["name", "apiKey", "model", "baseUrl", "priority"],
      );

  @override
  Future<AgentStatus> crateApiZeroclawAgentStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawAgentStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawAgentStatusConstMeta =>
      const TaskConstMeta(debugName: "agent_status", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<AgentStatus> crateApiZeroclawInitAgent({
    required String dataDir,
    required String strategy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          sse_encode_String(strategy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawInitAgentConstMeta,
        argValues: [dataDir, strategy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawInitAgentConstMeta => const TaskConstMeta(
    debugName: "init_agent",
    argNames: ["dataDir", "strategy"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<ProviderStatus>> crateApiZeroclawListProviders() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_provider_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawListProvidersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawListProvidersConstMeta =>
      const TaskConstMeta(debugName: "list_providers", argNames: []);

  @override
  Future<BigInt> crateApiZeroclawMemoryCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawMemoryCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawMemoryCountConstMeta =>
      const TaskConstMeta(debugName: "memory_count", argNames: []);

  @override
  Future<bool> crateApiZeroclawMemoryForget({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawMemoryForgetConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawMemoryForgetConstMeta =>
      const TaskConstMeta(debugName: "memory_forget", argNames: ["key"]);

  @override
  Future<MemoryEntryDto?> crateApiZeroclawMemoryGet({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_memory_entry_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawMemoryGetConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawMemoryGetConstMeta =>
      const TaskConstMeta(debugName: "memory_get", argNames: ["key"]);

  @override
  Future<bool> crateApiZeroclawMemoryHealth() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawMemoryHealthConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawMemoryHealthConstMeta =>
      const TaskConstMeta(debugName: "memory_health", argNames: []);

  @override
  Future<List<MemoryEntryDto>> crateApiZeroclawMemoryList({
    String? category,
    String? sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(category, serializer);
          sse_encode_opt_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_memory_entry_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawMemoryListConstMeta,
        argValues: [category, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawMemoryListConstMeta => const TaskConstMeta(
    debugName: "memory_list",
    argNames: ["category", "sessionId"],
  );

  @override
  Future<List<MemoryEntryDto>> crateApiZeroclawMemoryRecall({
    required String query,
    required int limit,
    String? sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_opt_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_memory_entry_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawMemoryRecallConstMeta,
        argValues: [query, limit, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawMemoryRecallConstMeta =>
      const TaskConstMeta(
        debugName: "memory_recall",
        argNames: ["query", "limit", "sessionId"],
      );

  @override
  Future<BigInt> crateApiZeroclawMemoryReindex() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawMemoryReindexConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawMemoryReindexConstMeta =>
      const TaskConstMeta(debugName: "memory_reindex", argNames: []);

  @override
  Future<void> crateApiZeroclawMemoryStore({
    required String key,
    required String content,
    required String category,
    String? sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(content, serializer);
          sse_encode_String(category, serializer);
          sse_encode_opt_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawMemoryStoreConstMeta,
        argValues: [key, content, category, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawMemoryStoreConstMeta =>
      const TaskConstMeta(
        debugName: "memory_store",
        argNames: ["key", "content", "category", "sessionId"],
      );

  @override
  Future<bool> crateApiZeroclawRemoveProvider({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawRemoveProviderConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawRemoveProviderConstMeta =>
      const TaskConstMeta(debugName: "remove_provider", argNames: ["name"]);

  @override
  Future<String> crateApiZeroclawRunAgent({
    required String prompt,
    String? sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(prompt, serializer);
          sse_encode_opt_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawRunAgentConstMeta,
        argValues: [prompt, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawRunAgentConstMeta => const TaskConstMeta(
    debugName: "run_agent",
    argNames: ["prompt", "sessionId"],
  );

  @override
  Future<String> crateApiZeroclawRunAgentWithProvider({
    required String prompt,
    required String providerName,
    String? sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(prompt, serializer);
          sse_encode_String(providerName, serializer);
          sse_encode_opt_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawRunAgentWithProviderConstMeta,
        argValues: [prompt, providerName, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawRunAgentWithProviderConstMeta =>
      const TaskConstMeta(
        debugName: "run_agent_with_provider",
        argNames: ["prompt", "providerName", "sessionId"],
      );

  @override
  Future<String> crateApiZeroclawSetRoutingStrategy({
    required String strategy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(strategy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawSetRoutingStrategyConstMeta,
        argValues: [strategy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawSetRoutingStrategyConstMeta =>
      const TaskConstMeta(
        debugName: "set_routing_strategy",
        argNames: ["strategy"],
      );

  @override
  Future<bool> crateApiZeroclawUpdateProviderKey({
    required String name,
    required String newApiKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(newApiKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawUpdateProviderKeyConstMeta,
        argValues: [name, newApiKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawUpdateProviderKeyConstMeta =>
      const TaskConstMeta(
        debugName: "update_provider_key",
        argNames: ["name", "newApiKey"],
      );

  @override
  Future<bool> crateApiZeroclawUpdateProviderModel({
    required String name,
    required String newModel,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(newModel, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZeroclawUpdateProviderModelConstMeta,
        argValues: [name, newModel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZeroclawUpdateProviderModelConstMeta =>
      const TaskConstMeta(
        debugName: "update_provider_model",
        argNames: ["name", "newModel"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentStatus dco_decode_agent_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return AgentStatus(
      initialized: dco_decode_bool(arr[0]),
      memoryBackend: dco_decode_String(arr[1]),
      dataDir: dco_decode_String(arr[2]),
      memoryCount: dco_decode_u_64(arr[3]),
      providerCount: dco_decode_u_32(arr[4]),
      routingStrategy: dco_decode_String(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  MemoryEntryDto dco_decode_box_autoadd_memory_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_memory_entry_dto(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<MemoryEntryDto> dco_decode_list_memory_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_memory_entry_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProviderStatus> dco_decode_list_provider_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_provider_status).toList();
  }

  @protected
  MemoryEntryDto dco_decode_memory_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MemoryEntryDto(
      id: dco_decode_String(arr[0]),
      key: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      category: dco_decode_String(arr[3]),
      timestamp: dco_decode_String(arr[4]),
      sessionId: dco_decode_opt_String(arr[5]),
      score: dco_decode_opt_box_autoadd_f_64(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  MemoryEntryDto? dco_decode_opt_box_autoadd_memory_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_memory_entry_dto(raw);
  }

  @protected
  ProviderStatus dco_decode_provider_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProviderStatus(
      name: dco_decode_String(arr[0]),
      model: dco_decode_String(arr[1]),
      baseUrl: dco_decode_String(arr[2]),
      priority: dco_decode_u_32(arr[3]),
      isHealthy: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentStatus sse_decode_agent_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_initialized = sse_decode_bool(deserializer);
    var var_memoryBackend = sse_decode_String(deserializer);
    var var_dataDir = sse_decode_String(deserializer);
    var var_memoryCount = sse_decode_u_64(deserializer);
    var var_providerCount = sse_decode_u_32(deserializer);
    var var_routingStrategy = sse_decode_String(deserializer);
    return AgentStatus(
      initialized: var_initialized,
      memoryBackend: var_memoryBackend,
      dataDir: var_dataDir,
      memoryCount: var_memoryCount,
      providerCount: var_providerCount,
      routingStrategy: var_routingStrategy,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  MemoryEntryDto sse_decode_box_autoadd_memory_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_memory_entry_dto(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<MemoryEntryDto> sse_decode_list_memory_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemoryEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_memory_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProviderStatus> sse_decode_list_provider_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProviderStatus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_provider_status(deserializer));
    }
    return ans_;
  }

  @protected
  MemoryEntryDto sse_decode_memory_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_key = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_opt_String(deserializer);
    var var_score = sse_decode_opt_box_autoadd_f_64(deserializer);
    return MemoryEntryDto(
      id: var_id,
      key: var_key,
      content: var_content,
      category: var_category,
      timestamp: var_timestamp,
      sessionId: var_sessionId,
      score: var_score,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MemoryEntryDto? sse_decode_opt_box_autoadd_memory_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_memory_entry_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProviderStatus sse_decode_provider_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_priority = sse_decode_u_32(deserializer);
    var var_isHealthy = sse_decode_bool(deserializer);
    return ProviderStatus(
      name: var_name,
      model: var_model,
      baseUrl: var_baseUrl,
      priority: var_priority,
      isHealthy: var_isHealthy,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_status(AgentStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.initialized, serializer);
    sse_encode_String(self.memoryBackend, serializer);
    sse_encode_String(self.dataDir, serializer);
    sse_encode_u_64(self.memoryCount, serializer);
    sse_encode_u_32(self.providerCount, serializer);
    sse_encode_String(self.routingStrategy, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_memory_entry_dto(
    MemoryEntryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_memory_entry_dto(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_memory_entry_dto(
    List<MemoryEntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_memory_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_provider_status(
    List<ProviderStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_provider_status(item, serializer);
    }
  }

  @protected
  void sse_encode_memory_entry_dto(
    MemoryEntryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.timestamp, serializer);
    sse_encode_opt_String(self.sessionId, serializer);
    sse_encode_opt_box_autoadd_f_64(self.score, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_memory_entry_dto(
    MemoryEntryDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_memory_entry_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_provider_status(
    ProviderStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_u_32(self.priority, serializer);
    sse_encode_bool(self.isHealthy, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
