// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `call_provider`, `parse_category_filter`, `parse_category`, `pick_providers`, `route_prompt`, `strategy_name`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AgentState`, `ProviderConfig`, `RegisteredProvider`, `RoutingStrategy`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<AgentStatus> initAgent({
  required String dataDir,
  required String strategy,
}) => RustLib.instance.api.crateApiZeroclawInitAgent(
  dataDir: dataDir,
  strategy: strategy,
);

Future<int> addProvider({
  required String name,
  required String apiKey,
  required String model,
  required String baseUrl,
  required int priority,
}) => RustLib.instance.api.crateApiZeroclawAddProvider(
  name: name,
  apiKey: apiKey,
  model: model,
  baseUrl: baseUrl,
  priority: priority,
);

Future<bool> removeProvider({required String name}) =>
    RustLib.instance.api.crateApiZeroclawRemoveProvider(name: name);

Future<List<ProviderStatus>> listProviders() =>
    RustLib.instance.api.crateApiZeroclawListProviders();

Future<String> setRoutingStrategy({required String strategy}) =>
    RustLib.instance.api.crateApiZeroclawSetRoutingStrategy(strategy: strategy);

Future<bool> updateProviderKey({
  required String name,
  required String newApiKey,
}) => RustLib.instance.api.crateApiZeroclawUpdateProviderKey(
  name: name,
  newApiKey: newApiKey,
);

Future<bool> updateProviderModel({
  required String name,
  required String newModel,
}) => RustLib.instance.api.crateApiZeroclawUpdateProviderModel(
  name: name,
  newModel: newModel,
);

Future<String> runAgent({required String prompt, String? sessionId}) => RustLib
    .instance
    .api
    .crateApiZeroclawRunAgent(prompt: prompt, sessionId: sessionId);

Future<String> runAgentWithProvider({
  required String prompt,
  required String providerName,
  String? sessionId,
}) => RustLib.instance.api.crateApiZeroclawRunAgentWithProvider(
  prompt: prompt,
  providerName: providerName,
  sessionId: sessionId,
);

Future<void> memoryStore({
  required String key,
  required String content,
  required String category,
  String? sessionId,
}) => RustLib.instance.api.crateApiZeroclawMemoryStore(
  key: key,
  content: content,
  category: category,
  sessionId: sessionId,
);

Future<List<MemoryEntryDto>> memoryRecall({
  required String query,
  required int limit,
  String? sessionId,
}) => RustLib.instance.api.crateApiZeroclawMemoryRecall(
  query: query,
  limit: limit,
  sessionId: sessionId,
);

Future<MemoryEntryDto?> memoryGet({required String key}) =>
    RustLib.instance.api.crateApiZeroclawMemoryGet(key: key);

Future<List<MemoryEntryDto>> memoryList({
  String? category,
  String? sessionId,
}) => RustLib.instance.api.crateApiZeroclawMemoryList(
  category: category,
  sessionId: sessionId,
);

Future<bool> memoryForget({required String key}) =>
    RustLib.instance.api.crateApiZeroclawMemoryForget(key: key);

Future<BigInt> memoryCount() =>
    RustLib.instance.api.crateApiZeroclawMemoryCount();

Future<bool> memoryHealth() =>
    RustLib.instance.api.crateApiZeroclawMemoryHealth();

Future<BigInt> memoryReindex() =>
    RustLib.instance.api.crateApiZeroclawMemoryReindex();

Future<AgentStatus> agentStatus() =>
    RustLib.instance.api.crateApiZeroclawAgentStatus();

/// Overall agent status snapshot.
class AgentStatus {
  final bool initialized;
  final String memoryBackend;
  final String dataDir;
  final BigInt memoryCount;
  final int providerCount;
  final String routingStrategy;

  const AgentStatus({
    required this.initialized,
    required this.memoryBackend,
    required this.dataDir,
    required this.memoryCount,
    required this.providerCount,
    required this.routingStrategy,
  });

  @override
  int get hashCode =>
      initialized.hashCode ^
      memoryBackend.hashCode ^
      dataDir.hashCode ^
      memoryCount.hashCode ^
      providerCount.hashCode ^
      routingStrategy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentStatus &&
          runtimeType == other.runtimeType &&
          initialized == other.initialized &&
          memoryBackend == other.memoryBackend &&
          dataDir == other.dataDir &&
          memoryCount == other.memoryCount &&
          providerCount == other.providerCount &&
          routingStrategy == other.routingStrategy;
}

/// Mirror of `MemoryEntry` — plain types for clean Dart codegen.
class MemoryEntryDto {
  final String id;
  final String key;
  final String content;
  final String category;
  final String timestamp;
  final String? sessionId;
  final double? score;

  const MemoryEntryDto({
    required this.id,
    required this.key,
    required this.content,
    required this.category,
    required this.timestamp,
    this.sessionId,
    this.score,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      key.hashCode ^
      content.hashCode ^
      category.hashCode ^
      timestamp.hashCode ^
      sessionId.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          key == other.key &&
          content == other.content &&
          category == other.category &&
          timestamp == other.timestamp &&
          sessionId == other.sessionId &&
          score == other.score;
}

/// Describes a registered provider's status.
class ProviderStatus {
  final String name;
  final String model;
  final String baseUrl;
  final int priority;
  final bool isHealthy;

  const ProviderStatus({
    required this.name,
    required this.model,
    required this.baseUrl,
    required this.priority,
    required this.isHealthy,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      model.hashCode ^
      baseUrl.hashCode ^
      priority.hashCode ^
      isHealthy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderStatus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          model == other.model &&
          baseUrl == other.baseUrl &&
          priority == other.priority &&
          isHealthy == other.isHealthy;
}
